### ISSUE TITLE
Having uninstalled Edscension, error after each combat

### ISSUE THREAD

**Issue by MrHrulgin** [ZenProductions/Edscension#1]
I uninstalled Edscension through KOL Mafia's script manager, but now I get this error after each combat: "Unable to invoke ed_postadventure.ash". I get why it can't, the file's gone. But why is Mafia still looking for it?

**Comment by Zen00** [comment]
Go to your preferences options and choose the automation section. There remove the names of automation scripts being used from the text fields.

**Comment by MrHrulgin** [comment]
Thank you.
